#!jinja 

CREATE or ALTER TABLE {{ database }}.FACT.FACT_INSURANCETRANSACTIONS (
	TRANSACTIONID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	POLICYKEY NUMBER(38,0) NOT NULL,
	CUSTOMERKEY NUMBER(38,0) NOT NULL,
	AGENTKEY NUMBER(38,0) NOT NULL,
	POLICYTXNTYPEKEY NUMBER(38,0) NOT NULL,
	TRANSACTIONDATE DATE NOT NULL,
	TRANSACTIONAMOUNT FLOAT,
	PREMIUMAMOUNT FLOAT,
	COVERAGEAMOUNT FLOAT,
	CLAIMAMOUNT FLOAT,
	CREATEDDATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LASTUPDATEDDATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);