CREATE SCHEMA IF NOT EXISTS CI_CD;

CREATE OR ALTER TABLE CI_CD.CONFIG 
(
    ID NUMBER(38, 0) AUTOINCREMENT START 1 INCREMENT 1,
    TYPE VARCHAR,
    SEQ_ORDER NUMBER(38, 0) NULL
    LASTMODIFIED_DATE  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT OVERWRITE INTO CI_CD.CONFIG (TYPE,SEQ_ORDER)
  VALUES
  ('DATABASE',1),
  ('SCHEMA',2)
  ('TABLE',3)
  ('STORED_PROCEDURE',4)
  ('VIEW',5);

CREATE OR ALTER TABLE CI_CD.CHANGE_HISTORY 
(

    CHANGE_ID NUMBER(38, 0) AUTOINCREMENT START 1 INCREMENT 1,
    VERSION_ID NUMBER(38, 0) NULL,
    DESCRIPTION VARCHAR,
    SCRIPT VARCHAR,
    SCRIPT_TYPE VARCHAR,
    MODIFIED_DATE  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR,
    INSTALLED_BY VARCHAR,
    INSTALLED_ON TIMESTAMP_LTZ
);
