#!jinja 

CREATE or ALTER TABLE {{ database }}.DIMENSION.DIM_POLICY_TXN_TYPE (
	POLICYTXNTYPEKEY NUMBER(38,0) NOT NULL,
	POLICYTXNTYPECODE VARCHAR(20),
	POLICYTXNTYPENAME VARCHAR(100),
	POLICYTXNTYPEDESCRIPTION VARCHAR(255),
	ISACTIVE BOOLEAN,
	CREATEDDATE DATE,
	LASTUPDATEDDATE DATE,
	primary key (POLICYTXNTYPEKEY)
);