#!jinja 

CREATE or ALTER TABLE {{ database }}.CI_CD.CUSTOMERS (
	CUSTOMER_ID NUMBER(19,0) autoincrement start 1 increment 1 noorder,
	FIRST_NAME VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='NAME'),
	LAST_NAME VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='NAME'),
	PHONE_NO VARCHAR(16777216),
	EMAIL VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	STATE VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='ADMINISTRATIVE_AREA_1'),
	AGE NUMBER(38,0) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='AGE'),
	LAST_MODIFIED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	MARITAL_STATUS VARCHAR(100),
	NUMBEROFDEPENDENTS NUMBER(38,0) DEFAULT 1
);