h# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install snowsql
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          content=(~/bin/snowsql -q "Select GET_DDL('Table', 'CI_CD.CHANGE_HISTORY',true);" -o output_format=psql -o header=false -o timing=false -o friendly=false )
          echo "$content"
      
      - name: Run queries
        uses: anecdotes-ai/snowflake-query@v1.2
        id: run_queries
        with:
            snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
            snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
            snowflake_username: ${{ secrets.SNOWFLAKE_USER }}
            snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
            SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
            queries: 'Select GET_DDL(''Table'', ''DWH_CI_CD.CI_CD.CHANGE_HISTORY'',true)'
            # single quote is escaped with another single quote
       
      - name: Version Query Validation
        run: |
          echo "${{contains(steps.run_queries.outputs.queries_output, '5.20.1')}}"

       - name: Overwrite file
        uses: BoundfoxStudios/action-write-file@v1        
        with:
            path: Scripts/CHANGE_HISTORY.sql
            write-mode: overwrite            
            contents: ${{contains(steps.run_queries.outputs.queries_output, '5.20.1')}}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'   
