[connections]
[connections.myconnection]
account = "oz49116.eu-west-2.aws"
user = "DAMODHARANSOUNDARARAJAN"
password = "Simhan09#"
warehouse = "COMPUTE_WH"
database = "PRD_SMNTC_LAYER"
schema = "PUBLIC
role ="SYSADMIN"